name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  format:
    name: Format
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Ensure swiftformat
        run: |
          if ! command -v swiftformat >/dev/null; then
            brew install swiftformat
          fi

      - name: Check code formatting
        run: ./scripts/format.sh

  lint:
    name: Lint
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Ensure swiftlint
        run: |
          if ! command -v swiftlint >/dev/null; then
            brew install swiftlint
          fi

      - name: Check code linting
        run: ./scripts/lint.sh

  test:
    name: Build and App Tests
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Ensure xcodegen & xcbeautify
        run: |
          if ! command -v xcodegen >/dev/null; then
            brew install xcodegen
          fi
          if ! command -v xcbeautify >/dev/null; then
            brew install xcbeautify
          fi

      - name: Run unit tests
        run: ./scripts/test.sh --coverage

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.json
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: true
